### PR TITLE
add txt file support and add KUAL extensions for user choice

### PR DESCRIPTION
**Pull request by cytown**
user can switch the open type in KOReader/HackedUpReader/Original Reader.

### CODE REVIEW

**Comment by cytown** [comment]
Why no one review this?

**Comment by houqp** [comment]
I would like to, but I am not familiar with the code base. I am waiting for @chrox to review since he also manages the release :)

Are you interested in being a maintainer of this project?

**Comment by cytown** [comment]
OK, why not:)  I hope we can find few useful cool features for this one...

**Comment by houqp** [comment]
Awesome, I will send you an email soon.

**Comment by chrox** [comment]
Looks good to me. Thanks. 👍

**Comment by houqp** [comment]
@cytown we have also given you write access to this repo so you can help maintain it in the future :) Look for github invite in your inbox.

**Comment by DesertHuYang** [comment]
When I  tried to install the version 0.6.5 using mrinstaller ,it kept showing destroying packages. No problem with 0.6.4. Firmware version is 5.8.9. Am I the only one encountering this problem ?

**Comment by cytown** [comment]
Did you use upgrade? Or fresh install?  Please try uninstall and clear install.

**Comment by DesertHuYang** [comment]
I've tried both.
Now I found the last hint is "the package doesn't match your device " or something. 
Can you please fix it (*^ω^*)?

**Comment by cytown** [comment]
Please try this one, and check the message.

If still happen, maybe I am using wrong package tool or wrong command to package it.

[kindle-kpvbooklet-0.6.5.zip](https://github.com/koreader/kpvbooklet/files/1016193/kindle-kpvbooklet-0.6.5.zip)

**Comment by DesertHuYang** [comment]
Thanks. I will try again.

**Pull request merged**
